global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi-beauty_'
    static_configs:
      - targets: ['host.docker.internal:8000']
        metrics_path: '/metrics'
        scrape_interval: 5s